########## basics ##########
# Whether to run as a daemon process
--daemonize=true
# Whether to enable optimizer
--enable_optimizer=true
# The default charset when a space is created
--default_charset=utf8
# The default collate when a space is created
--default_collate=utf8_bin
# Whether to use the configuration obtained from the configuration file
--local_config=true

########## logging ##########
# The directory to host logging files
--log_dir=logs
# Log level, 0, 1, 2, 3 for INFO, WARNING, ERROR, FATAL respectively
--minloglevel=0
# Verbose log level, 1, 2, 3, 4, the higher of the level, the more verbose of the logging
--v=0
# Maximum seconds to buffer the log messages
--logbufsecs=0
# Whether to redirect stdout and stderr to separate output files
--redirect_stdout=true
# Destination filename of stdout and stderr, which will also reside in log_dir.
--stdout_log_file=schedule-stdout.log
--stderr_log_file=schedule-stderr.log

--stderrthreshold=2
# wether logging files' name contain time stamp.
--timestamp_in_logfile_name=true

--meta_server_addrs=192.168.56.101:9559
--storage_http_addrs=192.168.56.101:19779
--hdfs_job_dir=hdfs://